version: 1.0.{build}
os: Windows Server 2012 R2
environment:
  WERCKER_ROOT: true
  nodejs_version: 0.10
  matrix:
  - GYP_MSVS_VERSION: 2012
  - GYP_MSVS_VERSION: 2013
install:
- ps: Install-Product node $env:nodejs_version
- npm install -g node-gyp
build: off
test_script:
- npm install --unsafe-perm
- node --version
- npm --version
- npm test
deploy: off
